name: companye
favicon: null
layout_spectrum: 0.48899
typography_spectrum: 0.40926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#b2b2b2'
    - '#919191'
    - '#3b3b3b'
  brandStrength: 0.852145976619795
  lightness: 0.30616348679177463
  saturation: 0.16120148543268442
  rhythmicContrast: 0.4093051089439541
purpose: []
