name: companye
favicon: null
layout_spectrum: 0.48335122829303145
typography_spectrum: 0.6538486266508698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.852145976619795
  lightness: 0.30616348679177463
  saturation: 0.16120148543268442
  rhythmicContrast: 0.4093051089439541
purpose: []
